server:
  port: 8080
  servlet:
    context-path: /poi

here-map:
  discover-api: https://discover.search.hereapi.com/v1/discover?at=
  geocode-api: https://geocode.search.hereapi.com/v1/geocode
  api-key: 5jyGy_o9WzMSzrDimWjieMQJAirWF7zNMMJ4knhpAMs
  restraunt-category-type: restaurant
  charging-stations-category-type: charging-stations
  parking-spot-category-type: parking-spots