package com.mbrdi.poi.poisearch.stub;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mbrdi.poi.poisearch.dtos.POIFinderResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

public class ChargingStationProviderTestStub {

  private static ObjectMapper objectMapper = new ObjectMapper();
  public static String discoverApi = "https://discover.search.hereapi.com/v1/discover?at=";
  public static String accessToken = "accessToken";
  public static String categoryType = "charging-stations";

  public static ResponseEntity getValidChargingStationsResponse() throws Exception{
    return new ResponseEntity<>(validChargingStationsResponseBody(), HttpStatus.OK);
  }

  public static POIFinderResponse validChargingStationsResponseBody()throws Exception{
    return objectMapper.readValue(validChargingStationsResponse, POIFinderResponse.class);
  }

  public static String validChargingStationsResponse = "{\n"
      + "  \"items\": [\n"
      + "    {\n"
      + "      \"title\": \"Electric Vehicle Charging Station\",\n"
      + "      \"id\": \"here:pds:place:276u33db-dfaa9b113b9143578202814d13327640\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Electric Vehicle Charging Station, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Unter den Linden 77\",\n"
      + "      \"id\": \"here:pds:place:276if4l9-678fef5324d90651b4846b61bbf5f233\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Unter den Linden 77, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 23:59\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT23H59M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Apcoa Parking Deutschland\",\n"
      + "      \"id\": \"here:pds:place:276u33db-9733d0fd242a44469b077ec4e66f42ff\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Apcoa Parking Deutschland, Unter den Linden, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51602,\n"
      + "        \"lng\": 13.38024\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51633,\n"
      + "          \"lng\": 13.38022\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 172,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Allego\",\n"
      + "      \"id\": \"here:pds:place:276u33db-0d0c7b48020e4737945ab60eee4064d2\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Allego, Behrenstraße, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.5152,\n"
      + "        \"lng\": 13.38431\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51536,\n"
      + "          \"lng\": 13.3843\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 454,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"AG Park & Charge im Bundesverband Solare Mobilität e.V.\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-164f2d1fab154eebbbecda661e03d5e6\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"AG Park & Charge im Bundesverband Solare Mobilität e.V., Wilhelmstraße 92, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Wilhelmstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"92\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.5125,\n"
      + "        \"lng\": 13.38222\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51261,\n"
      + "          \"lng\": 13.38281\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 486,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+4930326629990\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Inge-Beisheim-Platz\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-72f44eab929540bd9aa247fed2aec782\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Inge-Beisheim-Platz, Inge-Beisheim-Platz 1, 10785 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Tiergarten\",\n"
      + "        \"street\": \"Inge-Beisheim-Platz\",\n"
      + "        \"postalCode\": \"10785\",\n"
      + "        \"houseNumber\": \"1\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51089,\n"
      + "        \"lng\": 13.37599\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51083,\n"
      + "          \"lng\": 13.37584\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 569,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Allego GmbH\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-dae1217631ab490183459680f08beb25\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Allego GmbH, Voßstraße 23, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Voßstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"23\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51076,\n"
      + "        \"lng\": 13.37881\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51091,\n"
      + "          \"lng\": 13.37878\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 576,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Voßstraße\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-213d3bf07ba74d3594755abf91c32e40\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Voßstraße, Voßstraße 24, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Voßstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"24\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51078,\n"
      + "        \"lng\": 13.37904\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51093,\n"
      + "          \"lng\": 13.37901\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 576,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Allego GmbH\",\n"
      + "      \"id\": \"here:pds:place:276u33db-3c321752df2346da9f28f62cf7afe896\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Allego GmbH, Neustädtische Kirchstraße, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Neustädtische Kirchstraße\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51961,\n"
      + "        \"lng\": 13.38522\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51963,\n"
      + "          \"lng\": 13.3853\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 655,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Allego GmbH\",\n"
      + "      \"id\": \"here:pds:place:276u33db-280c5f9492934a62b429a2df65aebb75\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Allego GmbH, Neustädtische Kirchstraße 8, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Neustädtische Kirchstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"8\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51944,\n"
      + "        \"lng\": 13.38549\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51943,\n"
      + "          \"lng\": 13.38534\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 658,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Vattenfall\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-13202864d58d43fd890cf18fc27a1cc7\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Vattenfall, Leipziger Platz 19, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Leipziger Platz\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"19\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.50999,\n"
      + "        \"lng\": 13.37722\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.5099,\n"
      + "          \"lng\": 13.37738\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 658,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+498002335335\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Innogy Emobility Solutions\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-91216cb14a5745b6a7537d412b4d8a9d\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Innogy Emobility Solutions, Bellevuestraße, 10785 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Tiergarten\",\n"
      + "        \"street\": \"Bellevuestraße\",\n"
      + "        \"postalCode\": \"10785\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51043,\n"
      + "        \"lng\": 13.37384\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51051,\n"
      + "          \"lng\": 13.37387\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 662,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Allego GmbH\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-84a70464d9a04d8184999c7514a6c587\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Allego GmbH, Potsdamer Platz, 10785 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Tiergarten\",\n"
      + "        \"street\": \"Potsdamer Platz\",\n"
      + "        \"postalCode\": \"10785\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51,\n"
      + "        \"lng\": 13.37571\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51004,\n"
      + "          \"lng\": 13.3757\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 670,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Ladestation smart Innogy Se\",\n"
      + "      \"id\": \"here:pds:place:276u33d8-69960fa5cc044bc2bb9c20d8fc242884\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Ladestation smart Innogy Se, Bellevuestraße 3, 10785 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Tiergarten\",\n"
      + "        \"street\": \"Bellevuestraße\",\n"
      + "        \"postalCode\": \"10785\",\n"
      + "        \"houseNumber\": \"3\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51043,\n"
      + "        \"lng\": 13.37318\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51066,\n"
      + "          \"lng\": 13.37344\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 681,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+498002255793\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Ladestation smart Innogy Se - Emob\",\n"
      + "      \"id\": \"here:pds:place:276if4l9-eb0e0a863b8d094b94e16801b29bd6ff\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Ladestation smart Innogy Se - Emob, Bellevuestraße 3, 10785 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Tiergarten\",\n"
      + "        \"street\": \"Bellevuestraße\",\n"
      + "        \"postalCode\": \"10785\",\n"
      + "        \"houseNumber\": \"3\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51043,\n"
      + "        \"lng\": 13.37318\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51066,\n"
      + "          \"lng\": 13.37344\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 681,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+498002255793\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Innogy Emobility Solutions\",\n"
      + "      \"id\": \"here:pds:place:276u33db-a274d09b75fa49f3bb000de374e39cb0\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Innogy Emobility Solutions, Reinhardtstraße, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Reinhardtstraße\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.52282,\n"
      + "        \"lng\": 13.38097\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.5228,\n"
      + "          \"lng\": 13.38097\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 801,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Ladestation smart Innogy Se\",\n"
      + "      \"id\": \"here:pds:place:276u33db-971e61202d204d449e1bfd8dd2bc06a3\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Ladestation smart Innogy Se, Reinhardtstraße 32, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Reinhardtstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"32\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.52291,\n"
      + "        \"lng\": 13.38091\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.52281,\n"
      + "          \"lng\": 13.38102\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 809,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+498002255793\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Ladestation smart Innogy Se - Emob\",\n"
      + "      \"id\": \"here:pds:place:276if4l9-8aa392ee30450f0decab78d5d72d9194\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Ladestation smart Innogy Se - Emob, Reinhardtstraße 32, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Reinhardtstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"32\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.52291,\n"
      + "        \"lng\": 13.38091\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.52281,\n"
      + "          \"lng\": 13.38102\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 809,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+498002255793\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"RWE Effizienz GmbH\",\n"
      + "      \"id\": \"here:pds:place:276u33db-5d92d409475147339c9694b98e5e2b5b\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"RWE Effizienz GmbH, Behrenstraße 28, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"28\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51556,\n"
      + "        \"lng\": 13.38986\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.5157,\n"
      + "          \"lng\": 13.38983\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 824,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Ladestation smart Innogy Se - Emob\",\n"
      + "      \"id\": \"here:pds:place:276if4l9-9109ceb73b190492d281cc3f1b1c6e4d\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:ev_charging_station\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Ladestation smart Innogy Se - Emob, Behrenstraße 28, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"28\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51556,\n"
      + "        \"lng\": 13.38986\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.5157,\n"
      + "          \"lng\": 13.38983\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 824,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"700-7600-0322\",\n"
      + "          \"name\": \"Ladestation für Elektrofahrzeuge\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+498002255793\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    }\n"
      + "  ]\n"
      + "}";

}
