package com.mbrdi.poi.poisearch.stub;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mbrdi.poi.poisearch.dtos.POIFinderResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

public class ParkingSpotProviderTestStub {

  private static ObjectMapper objectMapper = new ObjectMapper();
  public static String discoverApi = "https://discover.search.hereapi.com/v1/discover?at=";
  public static String accessToken = "accessToken";
  public static String categoryType = "parking-spots";

  public static ResponseEntity getValidParkingSpotResponse() throws Exception{
    return new ResponseEntity<>(validParkingSpotResponseBody(), HttpStatus.OK);
  }

  public static POIFinderResponse validParkingSpotResponseBody()throws Exception{
    return objectMapper.readValue(validParkingSpotResponse, POIFinderResponse.class);
  }

  public static String validParkingSpotResponse = "{\n"
      + "  \"items\": [\n"
      + "    {\n"
      + "      \"title\": \"Parking Spot\",\n"
      + "      \"id\": \"here:pds:place:8409vg50-9c5d7485a5e845169b03b2852f14b798\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Parking Spot, 4505 Plaza Dr, Irving, TX 75063, United States\",\n"
      + "        \"countryCode\": \"USA\",\n"
      + "        \"countryName\": \"United States\",\n"
      + "        \"state\": \"Texas\",\n"
      + "        \"county\": \"Dallas\",\n"
      + "        \"city\": \"Irving\",\n"
      + "        \"street\": \"Plaza Dr\",\n"
      + "        \"postalCode\": \"75063\",\n"
      + "        \"houseNumber\": \"4505\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 32.91347,\n"
      + "        \"lng\": -97.01166\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 32.91336,\n"
      + "          \"lng\": -97.01176\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 8376710,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0178\",\n"
      + "          \"name\": \"Parking Lot\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0000\",\n"
      + "          \"name\": \"Parking\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"34073588\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"VGMSTlCNfQjwSa7Pcm6nHw\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+12145969829\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+19729153672\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.theparkingspot.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.theparkingspot.com/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://en.parkopedia.com/parking/garage/the_parking_spot_north/75063/irving/?vendor=here\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/locations/dallas/dfw/the-parking-spot-north\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"adensmore@theparkingspot.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Parking Spot - Haynes\",\n"
      + "      \"id\": \"here:pds:place:840dr5px-316e402def74413596805067cf38f51f\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Parking Spot - Haynes, US-1-9, Newark, NJ 07114, United States\",\n"
      + "        \"countryCode\": \"USA\",\n"
      + "        \"countryName\": \"United States\",\n"
      + "        \"state\": \"New Jersey\",\n"
      + "        \"county\": \"Essex\",\n"
      + "        \"city\": \"Newark\",\n"
      + "        \"street\": \"US-1-9\",\n"
      + "        \"postalCode\": \"07114\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 40.70079,\n"
      + "        \"lng\": -74.18685\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 40.70062,\n"
      + "          \"lng\": -74.18607\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 6395471,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0177\",\n"
      + "          \"name\": \"Parking Garage/Parking House\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0000\",\n"
      + "          \"name\": \"Parking\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0178\",\n"
      + "          \"name\": \"Parking Lot\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"41523314\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"oAduWu3DPdwGephvQuetDA\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+19732420649\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+19736212329\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.theparkingspot.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://en.parkopedia.com/parking/lot/the_parking_spot_haynes_ewr_airport/07114/newark/?vendor=here\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/reserve#/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/locations/new-york-newark/ewr/the-parking-spot-haynes\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Spot\",\n"
      + "      \"id\": \"here:pds:place:8408lxx5-00677870ef060dc646838c96e7bab61c\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Spot, 350 US Highway 1 and 9, Newark, NJ 07114, United States\",\n"
      + "        \"countryCode\": \"USA\",\n"
      + "        \"countryName\": \"United States\",\n"
      + "        \"state\": \"New Jersey\",\n"
      + "        \"county\": \"Essex\",\n"
      + "        \"city\": \"Newark\",\n"
      + "        \"street\": \"US Highway 1 and 9\",\n"
      + "        \"postalCode\": \"07114\",\n"
      + "        \"houseNumber\": \"350\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 40.6964,\n"
      + "        \"lng\": -74.18851\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 40.69632,\n"
      + "          \"lng\": -74.18837\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 6395910,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0177\",\n"
      + "          \"name\": \"Parking Garage/Parking House\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0000\",\n"
      + "          \"name\": \"Parking\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"41523315\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"jG8vnDHN97AVEx-ywomhLg\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+19736212329\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+19736249000\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"fax\": [\n"
      + "            {\n"
      + "              \"value\": \"+19738021191\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/locations/new-york-newark/ewr/spot\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/reserve#/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/locations/new-york-newark/ewr/the-parking-spot-haynes\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Wildpark Eekholt\",\n"
      + "      \"id\": \"here:pds:place:276u1x4u-c051fffafa034aaaa5aa53d50a13b774\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Wildpark Eekholt, Eckholt, 24576 Bimöhlen, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Schleswig-Holstein\",\n"
      + "        \"county\": \"Segeberg\",\n"
      + "        \"city\": \"Bimöhlen\",\n"
      + "        \"street\": \"Eckholt\",\n"
      + "        \"postalCode\": \"24576\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 53.94851,\n"
      + "        \"lng\": 10.02978\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 53.94825,\n"
      + "          \"lng\": 10.03006\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 273870,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"550-5520-0209\",\n"
      + "          \"name\": \"Wildpark\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"300-3000-0000\",\n"
      + "          \"name\": \"Sehenswürdigkeit\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5510-0202\",\n"
      + "          \"name\": \"Park/Freizeitfläche\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5510-0204\",\n"
      + "          \"name\": \"Gartenanlage\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5510-0206\",\n"
      + "          \"name\": \"Freizeitzentrum\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5520-0000\",\n"
      + "          \"name\": \"Freizeit\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5520-0208\",\n"
      + "          \"name\": \"Zoo\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5520-0210\",\n"
      + "          \"name\": \"Naturschutzgebiet\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"550-5520-0228\",\n"
      + "          \"name\": \"Tierpark\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"700-7200-0269\",\n"
      + "          \"name\": \"Organisationen und Gesellschaften\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"700-7400-0133\",\n"
      + "          \"name\": \"Reiseagentur\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0000\",\n"
      + "          \"name\": \"Parkplatz\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8600-0000\",\n"
      + "          \"name\": \"Sportanlage\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"58150061\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"2319396\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"oeThxqZfVwVv9kaKLByYFw\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"ypEgbuw-li_74oCubNy1CA\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+49432799230\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+494943279923\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+4949432799230\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"fax\": [\n"
      + "            {\n"
      + "              \"value\": \"+4943271232\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.wildpark-eekholt.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.wildpark-eekholt.de\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"info@wildpark-eekholt.de\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 09:00 - 16:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T090000\",\n"
      + "              \"duration\": \"PT09H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Parking Spot\",\n"
      + "      \"id\": \"here:pds:place:8408lxx5-ca30129cc3ff0c511e55d8e823110b0e\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Parking Spot, 19901 E 56th Ave, Aurora, CO 80019-2038, United States\",\n"
      + "        \"countryCode\": \"USA\",\n"
      + "        \"countryName\": \"United States\",\n"
      + "        \"state\": \"Colorado\",\n"
      + "        \"county\": \"Adams\",\n"
      + "        \"city\": \"Aurora\",\n"
      + "        \"district\": \"Green Valley Ranch\",\n"
      + "        \"street\": \"E 56th Ave\",\n"
      + "        \"postalCode\": \"80019-2038\",\n"
      + "        \"houseNumber\": \"19901\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 39.79861,\n"
      + "        \"lng\": -104.75022\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 39.79846,\n"
      + "          \"lng\": -104.75022\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 8149619,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0000\",\n"
      + "          \"name\": \"Parking\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0177\",\n"
      + "          \"name\": \"Parking Garage/Parking House\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"aYFIcbfuEx5GvRQpgfe27Q\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+13033734892\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/reserve#/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.theparkingspot.com/locations/denver/den/the-parking-spot\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"parkingviolation@gmail.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"City Quartier Dom Aquarée\",\n"
      + "      \"id\": \"here:pds:place:276u33dc-33ec154724f24dfb9d5fd54d46392c7e\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"City Quartier Dom Aquarée, Spandauer Straße 3, 10178 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Spandauer Straße\",\n"
      + "        \"postalCode\": \"10178\",\n"
      + "        \"houseNumber\": \"3\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.52018,\n"
      + "        \"lng\": 13.40414\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.52027,\n"
      + "          \"lng\": 13.40432\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 1851,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0177\",\n"
      + "          \"name\": \"Parkhaus\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8500-0000\",\n"
      + "          \"name\": \"Parkplatz\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1010620916\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493026071113\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"https://www.parkopedia.de/parken/tiefgarage/city_quartier_dom_aquar%C3%A9e_radisson_blu_hotel/10178/berlin/?vendor=here\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 00:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    }\n"
      + "  ]\n"
      + "}";


}
