package com.mbrdi.poi.poisearch.stub;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mbrdi.poi.poisearch.dtos.POIFinderResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

public class RestrauntProviderTestStub {

  private static ObjectMapper objectMapper = new ObjectMapper();
  public static String discoverApi = "https://discover.search.hereapi.com/v1/discover?at=";
  public static String accessToken = "accessToken";
  public static String categoryType = "restaurants";

  public static ResponseEntity getValidRestaurantsResponse() throws Exception{
    return new ResponseEntity<>(validRestaurantsResponseBody(), HttpStatus.OK);
  }

  public static POIFinderResponse validRestaurantsResponseBody()throws Exception{
    return objectMapper.readValue(validRestaurantsResponse, POIFinderResponse.class);
  }

  public static String validRestaurantsResponse = "{\n"
      + "  \"items\": [\n"
      + "    {\n"
      + "      \"title\": \"Die Ess-Bahn\",\n"
      + "      \"id\": \"here:pds:place:276u33db-377496066b324c069c4f190e17dd8063\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Die Ess-Bahn, Ebertstraße, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Ebertstraße\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51602,\n"
      + "        \"lng\": 13.37694\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51602,\n"
      + "          \"lng\": 13.37694\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 53,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"jAJNtQu9qxb1sKY4htoejQ\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"302-000\",\n"
      + "          \"name\": \"Deutsch\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493084370441\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 08:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T080000\",\n"
      + "              \"duration\": \"PT16H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Aadava\",\n"
      + "      \"id\": \"here:pds:place:2768lxx5-f5e49398b7090789d0cb9cc5075be8e5\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Aadava, Ebertstraße, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Ebertstraße\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51603,\n"
      + "        \"lng\": 13.37694\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51603,\n"
      + "          \"lng\": 13.37694\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 53,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"cl0Er-9Nh4aVZvQEYMKkdA\"\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"SUBWAY\",\n"
      + "      \"id\": \"here:pds:place:276u33db-a12941357727422e92ae85cb3533c136\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"SUBWAY, Pariser Platz, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Pariser Platz\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51657,\n"
      + "        \"lng\": 13.37835\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51649,\n"
      + "          \"lng\": 13.37837\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 87,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Mama Trattoria Berlin Pariser Platz\",\n"
      + "      \"id\": \"here:pds:place:276u33db-179d68383ad940deb57f49c339ec4b59\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Mama Trattoria Berlin Pariser Platz, Pariser Platz 6A, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Pariser Platz\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"6A\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51686,\n"
      + "        \"lng\": 13.37797\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51681,\n"
      + "          \"lng\": 13.37812\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 108,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"16673618\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"300-000\",\n"
      + "          \"name\": \"Europäisch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"304-000\",\n"
      + "          \"name\": \"Italienisch\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"372-000\",\n"
      + "          \"name\": \"Mediterran\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-057\",\n"
      + "          \"name\": \"Pizza\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-083\",\n"
      + "          \"name\": \"Naturkost/Vollwert\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493020219393\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.mama.eu\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.mama.eu/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.mama.eu/#\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"pariserplatz@mama.eu\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 11:30 - 23:30\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T113000\",\n"
      + "              \"duration\": \"PT12H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Hopfingerbräu am Brandenburger Tor\",\n"
      + "      \"id\": \"here:pds:place:276u33db-105c221362464a8cb3977a6c616baee9\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Hopfingerbräu am Brandenburger Tor, Ebertstraße 24, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Ebertstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"24\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51708,\n"
      + "        \"lng\": 13.37768\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51702,\n"
      + "          \"lng\": 13.37724\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 131,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0011\",\n"
      + "          \"name\": \"Bar oder Pub\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"300-3000-0350\",\n"
      + "          \"name\": \"Brauerei\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1193032637\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"1811655\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"qBfan4zQE4FBLY8mwjYl6Q\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"302-000\",\n"
      + "          \"name\": \"Deutsch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-064\",\n"
      + "          \"name\": \"International\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493020458637\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"fax\": [\n"
      + "            {\n"
      + "              \"value\": \"+493020607834\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"hopfingerbraeu-im-palais.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.bier-genuss.berlin/de/hopfingerbraeu-am-brandenburger-tor\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.hopfingerbraeu-im-palais.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.hopfingerbraeu-im-palais.de/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.bier-genuss.berlin/\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"info@hopfingerbraeu-im-palais.de\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 10:00 - 22:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T100000\",\n"
      + "              \"duration\": \"PT12H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"L'Ambasserie\",\n"
      + "      \"id\": \"here:pds:place:276u33db-0d5e54693a1c486b88abe6ba53b6731f\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"L'Ambasserie, Pariser Platz 5, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Pariser Platz\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"5\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51695,\n"
      + "        \"lng\": 13.37917\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51688,\n"
      + "          \"lng\": 13.37918\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 153,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"700-7200-0253\",\n"
      + "          \"name\": \"Catering und Gastronomiedienstleistungen\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"iUNcTOAZ8cyxLbStCnOv_Q\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"800-069\",\n"
      + "          \"name\": \"Gebäck\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+4915152321112\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+4917680383723\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.arianacook.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Fri: 09:30 - 18:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T093000\",\n"
      + "              \"duration\": \"PT08H30M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Café Voltaire in der Franz. Botschaft\",\n"
      + "      \"id\": \"here:pds:place:276t4x7z-a57058287bb50680c10dd422d360480e\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Café Voltaire in der Franz. Botschaft, Pariser Platz 5, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Pariser Platz\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"5\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51695,\n"
      + "        \"lng\": 13.37917\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51688,\n"
      + "          \"lng\": 13.37918\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 153,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1100-0010\",\n"
      + "          \"name\": \"Kaffeehaus\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0001\",\n"
      + "          \"name\": \"Speiselokal\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"700-7400-0285\",\n"
      + "          \"name\": \"Internetcafé\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"dZI1agFprfYIoXlDlyqZRw\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+4930590039511\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.botschaft-frankreich.de/\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Lorenz Adlon Esszimmer\",\n"
      + "      \"id\": \"here:pds:place:276u33db-cc50ca74bc7e4e19a646a85abd9ca9ee\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Lorenz Adlon Esszimmer, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"500-5000-0053\",\n"
      + "          \"name\": \"Hotel\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"500-5000-0000\",\n"
      + "          \"name\": \"Hotel oder Motel\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"700-7200-0264\",\n"
      + "          \"name\": \"Verwaltungs- und Beratungsdienstleistungen\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"chains\": [\n"
      + "        {\n"
      + "          \"id\": \"363\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"50671361\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"56115597\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"190694\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"715474\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"6BCLgz8j6j2em7XLLsXoow\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"E5rXZ283uIRiDem_pUzWiQ\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"RZtA3eVwENNPARFuJ_K6Rg\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"301-000\",\n"
      + "          \"name\": \"Französisch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"300-000\",\n"
      + "          \"name\": \"Europäisch\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"302-000\",\n"
      + "          \"name\": \"Deutsch\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022610\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+493022611959\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+493022611960\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+49303022610\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+493079745600\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+49493022610\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+49493022612222\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"fax\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022612222\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.hotel-adlon.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/adlon\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/adlon;http://www.kempinski.com/de/berlin/hotel-adlon/welcome;http://www.lorenzadlon-esszimmer.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/de/berlin/hotel-adlon\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/de/berlin/hotel-adlon/welcome/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/en/berlin/hotel-adlon/dining/lorenz-adlon-esszimmer/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.lorenzadlon-esszimmer.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.lorenzadlon-esszimmer.de/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.kempinski.com/en/berlin/hotel-adlon/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"lorenzadlon-esszimmer.de\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"adlon@kempinski.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"hotel.adlon@kempinski.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"lorenz.adlon@kempinski.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon, Tue, Sun: 00:00 - 24:00\",\n"
      + "            \"Wed-Sat: 00:00 - 24:00, 19:00 - 24:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T000000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T190000\",\n"
      + "              \"duration\": \"PT05H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:WE,TH,FR,SA\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Sra Bua\",\n"
      + "      \"id\": \"here:pds:place:276u33db-91f7a63c35204aaa8c0e37db39a535bc\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Sra Bua, Unter den Linden 72, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"72\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0001\",\n"
      + "          \"name\": \"Speiselokal\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0002\",\n"
      + "          \"name\": \"Gehobenes Restaurant\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0011\",\n"
      + "          \"name\": \"Bar oder Pub\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0368\",\n"
      + "          \"name\": \"Cocktail Lounge\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1110486943\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1148365416\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"4100675\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"lATpT6X5wm6J5wta1lyWRQ\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"205-000\",\n"
      + "          \"name\": \"Thailändisch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"200-000\",\n"
      + "          \"name\": \"Asiatisch\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"202-000\",\n"
      + "          \"name\": \"Indisch\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022611590\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"fax\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022611537\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/de/berlin/hotel-adlon/dining/restaurants/sra-bua-by-tim-raue/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.srabua-adlon.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.srabua-berlin.de\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"srabua.adlon@kempinski.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"srabua.berlin@kempinski.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 19:00 - 22:30\"\n"
      + "          ],\n"
      + "          \"isOpen\": false,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T190000\",\n"
      + "              \"duration\": \"PT03H30M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Lobby Lounge & Bar\",\n"
      + "      \"id\": \"here:pds:place:276u33db-7829d836caeb4f629e8ab9c5b5bdd361\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Lobby Lounge & Bar, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0011\",\n"
      + "          \"name\": \"Bar oder Pub\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1100-0010\",\n"
      + "          \"name\": \"Kaffeehaus\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0368\",\n"
      + "          \"name\": \"Cocktail Lounge\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"300-3000-0000\",\n"
      + "          \"name\": \"Sehenswürdigkeit\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1130148774\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"18937430\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"0Gly_8-3j3TohDqyBRabsw\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"usu3MtOjznR0gunTpsaCzQ\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022611959\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/de/berlin/hotel-adlon/dining/restaurants/restaurant-quarre\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/en/berlin/hotel-adlon/dining/bars/lobby-lounge-and-bar/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"https://www.kempinski.com/de/berlin/hotel-adlon/dining/lobby-lounge-und-bar/\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"quarre.adlon@kempinski.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 06:30 - 01:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T063000\",\n"
      + "              \"duration\": \"PT04H30M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T063000\",\n"
      + "              \"duration\": \"PT04H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Adlon To Go\",\n"
      + "      \"id\": \"here:pds:place:276u33db-53d3aead970b249df0319b50f503a768\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Adlon To Go, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1100-0010\",\n"
      + "          \"name\": \"Kaffeehaus\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"10224657\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"I_OlYbaNC9M2tDluT4fM8w\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"302-000\",\n"
      + "          \"name\": \"Deutsch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-064\",\n"
      + "          \"name\": \"International\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+49493022610\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/adlon\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 09:00 - 18:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T090000\",\n"
      + "              \"duration\": \"PT09H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Curry Wolf\",\n"
      + "      \"id\": \"here:pds:place:276u33db-1e0e990004b9462b95494d7f984419f4\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Curry Wolf, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0009\",\n"
      + "          \"name\": \"Fastfood\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"600-6900-0103\",\n"
      + "          \"name\": \"Geschenkartikel, Antiquitäten und Kunsthandwerk\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"16959195\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"_LnJ-1dNn4C94UC0Yo3y2w\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"302-000\",\n"
      + "          \"name\": \"Deutsch\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493030839434\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+493033937339\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.curry-wolf.de\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sat: 10:00 - 20:00\",\n"
      + "            \"Sun: 11:00 - 20:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T100000\",\n"
      + "              \"duration\": \"PT10H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T110000\",\n"
      + "              \"duration\": \"PT09H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Quarré\",\n"
      + "      \"id\": \"here:pds:place:276u33db-14250949cc364d6bbaad7797394cfa44\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Quarré, Unter den Linden 77, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"77\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51612,\n"
      + "        \"lng\": 13.38003\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51631,\n"
      + "          \"lng\": 13.37999\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 160,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"56121722\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"1887582\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"rCgyLekViYw4gt2PrjzgQQ\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"301-000\",\n"
      + "          \"name\": \"Französisch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"300-000\",\n"
      + "          \"name\": \"Europäisch\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"302-000\",\n"
      + "          \"name\": \"Deutsch\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022611555\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+493022611959\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"fax\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022612222\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.hotel-adlon.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/de/berlin/hotel-adlon/dining/restaurants/restaurant-quarre/\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.kempinski.com/en/berlin/hotel-adlon/dining/restaurant-quarre/\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"quarre.adlon@kempinski.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sat: 12:00 - 15:00, 18:00 - 22:00\",\n"
      + "            \"Sun: 12:30 - 15:00, 18:00 - 22:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T120000\",\n"
      + "              \"duration\": \"PT03H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T180000\",\n"
      + "              \"duration\": \"PT04H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T123000\",\n"
      + "              \"duration\": \"PT02H30M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"China Club Berlin\",\n"
      + "      \"id\": \"here:pds:place:276u33db-cf961f2114a04f9f8c6099f253427b68\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"China Club Berlin, Behrenstraße 72, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"72\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51494,\n"
      + "        \"lng\": 13.37952\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51478,\n"
      + "          \"lng\": 13.3796\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 163,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"700-7200-0264\",\n"
      + "          \"name\": \"Verwaltungs- und Beratungsdienstleistungen\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"800-8700-0296\",\n"
      + "          \"name\": \"Clubhaus\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"201-000\",\n"
      + "          \"name\": \"Chinesisch\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+4930209120\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+493030209120\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.china-club-berlin.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.china-club-berlin.de/\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 09:00 - 13:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": false,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T090000\",\n"
      + "              \"duration\": \"PT04H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"China Club Berlin\",\n"
      + "      \"id\": \"here:pds:place:276u33db-acbff2a574ae4d2287990fa908605cbd\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"China Club Berlin, Behrenstraße 72, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"72\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51494,\n"
      + "        \"lng\": 13.37952\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51478,\n"
      + "          \"lng\": 13.3796\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 163,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1100-0000\",\n"
      + "          \"name\": \"Kaffee/Tee\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0368\",\n"
      + "          \"name\": \"Cocktail Lounge\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"11880656\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"12321560\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"Qa0-mSO6kUTRM5eF7Hyjsg\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"jtHCxYTmz1Mdc3R5bB7VYg\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"202-000\",\n"
      + "          \"name\": \"Indisch\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"201-000\",\n"
      + "          \"name\": \"Chinesisch\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493020628610\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+494930209120\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.china-club-berlin.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.india-club-berlin.com\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.india-club-berlin.com/\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"info@india-club-berlin.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 09:00 - 01:00, 18:00 - 23:30\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T090000\",\n"
      + "              \"duration\": \"PT16H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T180000\",\n"
      + "              \"duration\": \"PT05H30M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Sra Bua by Tim Raue\",\n"
      + "      \"id\": \"here:pds:place:276u33db-3815536020f0403b02175f9988a4ec9e\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Sra Bua by Tim Raue, Behrenstraße 72, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"72\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51494,\n"
      + "        \"lng\": 13.37952\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51478,\n"
      + "          \"lng\": 13.3796\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 163,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1110486076\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"800-066\",\n"
      + "          \"name\": \"Fusion\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493020628610\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://srabua.berlin\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"email\": [\n"
      + "            {\n"
      + "              \"value\": \"srabua.berlin@kempinski.com\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Tue-Sat: 19:00 - 22:30\"\n"
      + "          ],\n"
      + "          \"isOpen\": false,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T190000\",\n"
      + "              \"duration\": \"PT03H30M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:TU,WE,TH,FR,SA\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"After Work Party Berlin\",\n"
      + "      \"id\": \"here:pds:place:276u33db-214e764670a844b3a0dc7e039abb5249\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"After Work Party Berlin, Behrenstraße 72, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"72\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51494,\n"
      + "        \"lng\": 13.37952\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51478,\n"
      + "          \"lng\": 13.3796\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 163,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"200-2000-0012\",\n"
      + "          \"name\": \"Nachtclub\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0001\",\n"
      + "          \"name\": \"Speiselokal\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"800-078\",\n"
      + "          \"name\": \"Grillgerichte\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+4970072727299\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.after-work-party.biz\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"The Krug Room Berlin im Uma Restaurant\",\n"
      + "      \"id\": \"here:pds:place:276l18c2-813e583ff63f01157cefbadc98fa6bcf\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"The Krug Room Berlin im Uma Restaurant, Behrenstraße 72, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Behrenstraße\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"72\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51494,\n"
      + "        \"lng\": 13.37952\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51478,\n"
      + "          \"lng\": 13.3796\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 163,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1193852593\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"RPDnQ2jD_lK0ortOrv6wAw\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"pMVlaF-uZm9gfmEama-G2A\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022611959\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+4930301117159\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sat: 18:00 - 23:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": false,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T180000\",\n"
      + "              \"duration\": \"PT05H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Häagen-Dazs\",\n"
      + "      \"id\": \"here:pds:place:276u33db-286e284e1be948dabec1637464ce3d5d\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Häagen-Dazs, Unter den Linden 80, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\",\n"
      + "        \"houseNumber\": \"80\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51674,\n"
      + "        \"lng\": 13.38004\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51658,\n"
      + "          \"lng\": 13.38006\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 184,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1100-0010\",\n"
      + "          \"name\": \"Kaffeehaus\",\n"
      + "          \"primary\": true\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0000\",\n"
      + "          \"name\": \"Restaurant\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"100-1100-0000\",\n"
      + "          \"name\": \"Kaffee/Tee\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"id\": \"600-6300-0066\",\n"
      + "          \"name\": \"Supermarkt\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"references\": [\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"core\"\n"
      + "          },\n"
      + "          \"id\": \"1147112655\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"tripadvisor\"\n"
      + "          },\n"
      + "          \"id\": \"4748983\"\n"
      + "        },\n"
      + "        {\n"
      + "          \"supplier\": {\n"
      + "            \"id\": \"yelp\"\n"
      + "          },\n"
      + "          \"id\": \"z9DFRp0lfC3nF9s_wjZV1Q\"\n"
      + "        }\n"
      + "      ],\n"
      + "      \"foodTypes\": [\n"
      + "        {\n"
      + "          \"id\": \"800-063\",\n"
      + "          \"name\": \"Eis\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493020641795\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"+49447882653670\"\n"
      + "            }\n"
      + "          ],\n"
      + "          \"www\": [\n"
      + "            {\n"
      + "              \"value\": \"http://www.haagen-dazs.de\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"value\": \"http://www.haagen-dazs.de/\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ],\n"
      + "      \"openingHours\": [\n"
      + "        {\n"
      + "          \"text\": [\n"
      + "            \"Mon-Sun: 12:00 - 18:00\"\n"
      + "          ],\n"
      + "          \"isOpen\": true,\n"
      + "          \"structured\": [\n"
      + "            {\n"
      + "              \"start\": \"T120000\",\n"
      + "              \"duration\": \"PT06H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:MO,TU,WE,TH,FR,SA,SU\"\n"
      + "            },\n"
      + "            {\n"
      + "              \"start\": \"T180000\",\n"
      + "              \"duration\": \"PT24H00M\",\n"
      + "              \"recurrence\": \"FREQ:DAILY;BYDAY:FR\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    },\n"
      + "    {\n"
      + "      \"title\": \"Adlon To Go\",\n"
      + "      \"id\": \"here:pds:place:276u33db-d7950e0b9afb7c142a3d44502372f39c\",\n"
      + "      \"ontologyId\": \"here:cm:ontology:restaurant\",\n"
      + "      \"resultType\": \"place\",\n"
      + "      \"address\": {\n"
      + "        \"label\": \"Adlon To Go, Unter den Linden, 10117 Berlin, Deutschland\",\n"
      + "        \"countryCode\": \"DEU\",\n"
      + "        \"countryName\": \"Deutschland\",\n"
      + "        \"state\": \"Berlin\",\n"
      + "        \"county\": \"Berlin\",\n"
      + "        \"city\": \"Berlin\",\n"
      + "        \"district\": \"Mitte\",\n"
      + "        \"street\": \"Unter den Linden\",\n"
      + "        \"postalCode\": \"10117\"\n"
      + "      },\n"
      + "      \"position\": {\n"
      + "        \"lat\": 52.51647,\n"
      + "        \"lng\": 13.38028\n"
      + "      },\n"
      + "      \"access\": [\n"
      + "        {\n"
      + "          \"lat\": 52.51647,\n"
      + "          \"lng\": 13.38028\n"
      + "        }\n"
      + "      ],\n"
      + "      \"distance\": 186,\n"
      + "      \"categories\": [\n"
      + "        {\n"
      + "          \"id\": \"100-1000-0001\",\n"
      + "          \"name\": \"Speiselokal\",\n"
      + "          \"primary\": true\n"
      + "        }\n"
      + "      ],\n"
      + "      \"contacts\": [\n"
      + "        {\n"
      + "          \"phone\": [\n"
      + "            {\n"
      + "              \"value\": \"+493022614981\"\n"
      + "            }\n"
      + "          ]\n"
      + "        }\n"
      + "      ]\n"
      + "    }\n"
      + "  ]\n"
      + "}";

}
